trigger:
- release/*
- feature/*
- bugfix/*
- hotfix/*

pr:
- master
- develop

stages:
- stage: Build
  displayName: 'Unix Build'
  jobs:
  - job:
    strategy:
      matrix:
        agent-ubuntu-16.04--compilerVersion-7--buildType-Release:
          agent: 'ubuntu-16.04'
          compilerVersion: '9'
          buildType: 'Release'
    pool:
      vmImage: $(agent)
    steps:
    - task: CMake@1
      inputs:
        workingDirectory: build
        cmakeArgs: .. -DCC=gcc-$(compilerVersion) -DCXX=g++-$(compilerVersion) -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$(buildType)

    - bash: |
        cd build
        make
      displayName: 'Make'

    - publish: build
      artifact: build_$(agent)_gcc$(compilerVersion)_$(buildType)

- stage: Test
  displayName: 'Unix Test'
  dependsOn: Build
  jobs:
  - job:
    strategy:
      matrix:
        agent-ubuntu-16.04--compilerVersion-7--buildType-Release:
          agent: 'ubuntu-16.04'
          compilerVersion: '9'
          buildType: 'Release'
    pool:
      vmImage: $(agent)
    steps:
    - download: current
      artifact: build_$(agent)_gcc$(compilerVersion)_$(buildType)

    - bash: |
        pwd && ls -alr
        cd $(Pipeline.Workspace)/build_$(agent)_gcc$(compilerVersion)_$(buildType)
        pwd && ls -alr
        chmod -R a+x ./hello_test   # artifacts do not preserve file permissions (https://github.com/microsoft/azure-pipelines-tasks/issues/6364)
        ./hello_test                # ctest dummy runnable
      displayName: 'Test'

- stage: Deploy
  displayName: 'Unix Deploy'
  dependsOn: Build
  jobs:
  - job: 
    steps:
    - bash:
        echo 'Deployment still to be defined'



