trigger:
- release/*
- feature/*
- bugfix/*
- hotfix/*

pr:
- master
- develop

jobs:
# GCC7 build pipeline
- job: gcc7
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'
      ubuntu-16.04:
        imageName: 'ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - bash: |
      sudo apt -y install gcc-7 g++-7 gcc-9 g++-9 
    displayName: 'Install Dependencies'
  - bash: |
      export CC=gcc-7
      export CXX=g++-7
      mkdir build_release
      cd build_release
      cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
    displayName: 'Configure Release'
  - bash: |
      cd build_release
      make
    displayName: 'Build Release'
  - bash: |
      cd build_release
      ./hello_test # ctest dummy
    displayName: 'Test Release'
  - bash: |
      export CC=gcc-7
      export CXX=g++-7
      mkdir build_debug
      cd build_debug
      cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug
    displayName: 'Configure Debug'
  - bash: |
      cd build_debug
      make
    displayName: 'Build Debug'
  - bash: |
      cd build_debug
      ./hello_test # ctest dummy
    displayName: 'Test Debug'
  - bash: |
      rm -rf build_debug
      rm -rf build_release
    displayName: 'Cleanup'

# GCC9 build pipeline
- job: gcc9
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'
      ubuntu-16.04:
        imageName: 'ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - bash: |
      sudo apt -y install gcc-7 g++-7 gcc-9 g++-9 
    displayName: 'Install Dependencies'
  - bash: |
      export CC=gcc-9
      export CXX=g++-9
      mkdir build_release
      cd build_release
      cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
    displayName: 'Configure Release'
  - bash: |
      cd build_release
      make
    displayName: 'Build Release'
  - bash: |
      cd build_release
      ./hello_test # ctest dummy
    displayName: 'Test Release'
  - bash: |
      export CC=gcc-9
      export CXX=g++-9
      mkdir build_debug
      cd build_debug
      cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug
    displayName: 'Configure Debug'
  - bash: |
      cd build_debug
      make
    displayName: 'Build Debug'
  - bash: |
      cd build_debug
      ./hello_test # ctest dummy
    displayName: 'Test Debug'
  - bash: |
      rm -rf build_debug
      rm -rf build_release
    displayName: 'Cleanup'


