trigger:
- release/*
- feature/*
- bugfix/*
- hotfix/*

pr:
- master
- develop

stages:
- stage: UnixBuildTest
  displayName: 'Unix Build & Test'
  jobs:
    - job:
      strategy:
        matrix:
          gcc7:
            compilerVersion: '7'
          gcc9:
            compilerVersion: '9'
          Release:
            buildType: 'Release'
          Debug:
            buildType: 'Debug'
          ubuntu-18.04:
            imageName: 'ubuntu-18.04'
          ubuntu-16.04:
            imageName: 'ubuntu-16.04'
      steps:
      - bash: |
          sudo apt -y install gcc-$(compilerVersion) g++-$(compilerVersion)
        displayName: 'Install Dependencies'

      - bash: |
          export CC=gcc-$(compilerVersion)
          export CXX=g++-$(compilerVersion)
          mkdir build_gcc$(compilerVersion)_$(buildType)
          cd build_gcc$(compilerVersion)_$(buildType)
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$(buildType)
        displayName: 'Configure'

      - bash: |
          cd build_gcc$(compilerVersion)_$(buildType)
          make
        displayName: 'Build'
        
      - bash: |
          cd build_gcc$(compilerVersion)_$(buildType)
          ./hello_test # ctest dummy
        displayName: 'Test'
        
- stage: UnixDeploy
  displayName: 'Unix Deploy'
  dependsOn: UnixBuildTest
  jobs:
    - job: 
      steps:
      - bash:
          echo 'Deployment still to be defined'



