name: CPU-MSVC-Build-and-Test

on:
  push:
    branches:
        - master
        - develop
        - release/*

jobs:
  MSVC:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-2019, windows-latest]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Configure Release
      run: |
        mkdir build_release
        cd build_release
        cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: Build Release
      run: |
        cd build_release
        msbuild ALL_BUILD.vcxproj /p:Configuration=Release
    - name: Test Release
      run: |
        cd build_release
        cd Release
        ./Exe.exe # ctest

    - name: Configure Debug
      run: |
        mkdir build_debug
        cd build_debug
        cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: Build Debug
      run: |
        cd build_debug
        msbuild ALL_BUILD.vcxproj /p:Configuration=Debug
    - name: Test Debug
      run: |
        cd build_debug
        cd Debug
        ./Exe.exe
